### ISSUE TITLE
It doesn't compile

### ISSUE THREAD

**Issue by samanat** [firedog1024/arduino-uno-wifi-iotc#1]
Hi, 
I get 
```
exit status 1
Error compiling for board Arduino Uno WiFi Rev2.
```
By breaking the code into pieces and trying, I found out that the problem is in setup, at lines:
`mqtt_client->setCallback(callback);`
and
`String sasToken = createIotHubSASToken(devKey, url, expire);`

Can you give any help on this? Maybe I need the right version of a library to get this to work?

I am using an arduino uno wifi rev2.

**Comment by samanat** [comment]
In the function createIotHubSASToken
the problematic line is: 
int decodedKeyLength = base64_dec_len(key, keyLength);

**Comment by firedog1024** [comment]
Strange as the base64 implementation is handled not by a library but by the base64 source code included with the project.  One thing I noticed when trying to repo theis issue is that I initially developed this code using Visual Studio Code and the Arduino plug-in.  When doing this you don't have to put the .ino file into a directory of the same name as the ino file.  When I repo'd on the Arduino IDE I obviously had to create the needed directory and copy in all the source files into that directory.  When you did that did you copy all the files into the directory or just the uno_wifi.ino file?  If you don't copy all the files in then there is the likelyhood that the compiler looks in the Arduino  libraries you have for a base64 library and then issues occur.  If that solves the problem then great, else reply back and we can debug further.

**Comment by samanat** [comment]
Indeed, that was the problem. Initially I didn't copy the files in the same folder, but just changed the include paths in the files to absolute paths. Now, that I copied the files to the same folder as the .ino, I kept the relative paths and it worked. 
Thanks.
