### ISSUE TITLE
Can't get mqtt to connect

### ISSUE THREAD

**Issue by samanat** [firedog1024/arduino-uno-wifi-iotc#3]
The mqtt_client doesn't connect. 
I am constantly getting mqtt failed, rc=-1
Can you please verify that it still works with IoT Central as you describe?

**Comment by samanat** [comment]
firedog1024 told "offline" that he tried it and it worked, so I am closing this while I try to make my solution to work.. I am getting rc=5 now.. Different connection issue..

**Comment by skuppens** [comment]
Hi Samanat,
Did you resolve the RC=5 issue? I get the same error.
Everything comiles fine, but rc=5. This has something to do with unauthorized orr connection refused.

In Azure I have my device as "real" and unblocked...
Any ideas?

**Comment by samanat** [comment]
Hi skuppens, yes, I solved it by adding delays.. I believe a delay(1000) after wifi connected, will fix the issue..

**Comment by skuppens** [comment]
> 
> 
> Hi skuppens, yes, I solved it by adding delays.. I believe a delay(1000) after wifi connected, will fix the issue..

Worked for me as well...
I thought it would have been something with the construction of the username, SASToken or DevideID...
Thank you!
